# Numetron — Compile-time and runtime arbitrary-precision arithmetic
# (c) Alexander Pototskiy
# Licensed under the MIT License. See LICENSE file for details.

# sqr_basecase_adx.s -- schoolbook squaring with mulx + adcx/adox (BMI2 + ADX).
#
#   void numetron_sqr_basecase_adx(uint64_t* rp, const uint64_t* up, size_t n);
#
# rp[0..2n) = u[0..n)^2, n >= 2, rp not overlapping u. Half the products of u * u:
#
# 1. The products above the diagonal, once. Row i (0 <= i < n - 1) multiplies u[i+1..n) by u[i]
#    at rp[2i+1]: row 0 writes rp[1..n], each further row adds into rp[2i+1..i+n) and writes the
#    limb above, rp[i+n]. The rows are those of mul_basecase_adx.s -- two carry chains (adcx adds
#    the previous high half, adox adds rp), a 16-limb unrolled body entered at step -L & 15 for a
#    row of L limbs from a jump table -- only the entry is found per row here, as the rows get
#    shorter by one limb each (L = n - 1 - i). All rows in one call: no per-row call, which is
#    what made the rows of separate mul_1 / addmul_1 calls lose to the general product below
#    ~14 limbs.
# 2. One pass doubling that and adding the diagonal, two limbs (rp[2i], rp[2i+1]) per limb of u:
#    adox x, x doubles x, taking in the bit shifted out of the limb below (OF chain); adcx adds a
#    half of u[i]^2 (CF chain). rp[0] and rp[2n-1] are zero going in. A 4-step unrolled body
#    entered at step -n & 3 the same way.
#
# Short rows are straight-line code instead: their set-up (the entry, the counters) costs about
# as much as their products (~1 ns a row; the looped rows were ~27% slower than straight-line
# code at n = 16, 2026-09-27). For n <= 16 each n has straight-line code of its own,
# generated by the macros below with every offset fixed, in caller-saved registers only; above
# 16 only the rows of 16 limbs and more loop, and the last 15 rows -- always those of a 16-limb
# square of u's top 16 limbs -- are the straight-line rows of n = 16 at shifted pointers.
#
# SysV x64: rdi rp, rsi up, rdx n. Registers:
#   rdx  u[i] (mulx's implicit operand)      rsi  up cursor         rdi  rp cursor
#   rax  low half / sum                      r8, r9  high halves (even / odd steps)
#   rcx  pass counter (jrcxz)                r10  8 * k             r11  entry
#   rbx  rp + 2i + 1 (the row's start)       r12  up + i            r13  L, the row's length
#   r14  n                                   r15  rp                rbp  up

    .text

.macro MSTEP s
    .if \s % 2
    mulx    8*\s(%rsi), %rax, %r9
    adcx    %r8, %rax
    .else
    mulx    8*\s(%rsi), %rax, %r8
    adcx    %r9, %rax
    .endif
    mov     %rax, 8*\s(%rdi)
.endm

.macro ASTEP s
    .if \s % 2
    mulx    8*\s(%rsi), %rax, %r9
    adcx    %r8, %rax                   # + previous high half (CF chain)
    .else
    mulx    8*\s(%rsi), %rax, %r8
    adcx    %r9, %rax
    .endif
    adox    8*\s(%rdi), %rax            # + rp[i] (OF chain)
    mov     %rax, 8*\s(%rdi)
.endm

# rp[2s], rp[2s+1] = 2 * (rp[2s], rp[2s+1]) + u[s]^2 (+ both chains' carries)
.macro DSTEP s
    mov     8*\s(%rsi), %rdx
    mulx    %rdx, %rax, %r8             # u[s]^2 = r8:rax
    mov     16*\s(%rdi), %r9
    adox    %r9, %r9                    # doubled (OF chain)
    adcx    %rax, %r9                   # + low half (CF chain)
    mov     %r9, 16*\s(%rdi)
    mov     16*\s+8(%rdi), %r10
    adox    %r10, %r10
    adcx    %r8, %r10                   # + high half
    mov     %r10, 16*\s+8(%rdi)
.endm

# Row set-up: rsi, rdi = the row's up / rp start moved back k limbs, rcx = ceil(L / 16) passes,
# r11 = the entry from the table, both high halves and both flags zero. In: r13 = L, rdx = u[i].
.macro ROWSETUP tab, up, rp
    mov     %r13, %r10
    neg     %r10
    and     $15, %r10                   # k = -L & 15, the entry step
    lea     15(%r13), %rcx
    shr     $4, %rcx                    # passes: ceil(L / 16)
    lea     \tab(%rip), %r11
    movslq  (%r11,%r10,4), %rax
    add     %rax, %r11
    shl     $3, %r10                    # 8k: the pointers start k limbs early
    lea     \up, %rsi
    sub     %r10, %rsi
    mov     \rp, %rdi
    sub     %r10, %rdi
    xor     %r8d, %r8d
    xor     %r9d, %r9d                  # high halves = 0, CF = OF = 0
.endm

# ---- straight-line code for a fixed n (rsi up, rdi rp) ----

# rp[1..n] = u[1..n) * u[0]; step t multiplies u[1+t], the high halves alternating r8 / r9
.macro SROW0 n
    mov     (%rsi), %rdx
    xor     %r9d, %r9d                  # previous high half = 0, CF = OF = 0
    .set    t, 0
    .rept   \n - 1
    .set    d, 8 * (1 + t)
    .if t % 2
    mulx    d(%rsi), %rax, %r9
    adcx    %r8, %rax
    .else
    mulx    d(%rsi), %rax, %r8
    adcx    %r9, %rax
    .endif
    mov     %rax, d(%rdi)
    .set    t, t + 1
    .endr
    mov     $0, %eax                    # mov keeps the flags
    .set    d, 8 * \n
    .if (\n - 2) % 2                    # the last step's high half
    adcx    %rax, %r9
    mov     %r9, d(%rdi)
    .else
    adcx    %rax, %r8
    mov     %r8, d(%rdi)
    .endif
.endm

# rp[2i+1..i+n) += u[i+1..n) * u[i], rp[i+n] = the limb above
.macro SROW i, n
    mov     8 * \i(%rsi), %rdx
    xor     %r9d, %r9d
    .set    t, 0
    .rept   \n - 1 - \i
    .set    du, 8 * (\i + 1 + t)
    .set    dr, 8 * (2 * \i + 1 + t)
    .if t % 2
    mulx    du(%rsi), %rax, %r9
    adcx    %r8, %rax
    .else
    mulx    du(%rsi), %rax, %r8
    adcx    %r9, %rax
    .endif
    adox    dr(%rdi), %rax
    mov     %rax, dr(%rdi)
    .set    t, t + 1
    .endr
    mov     $0, %eax
    .set    dr, 8 * (\i + \n)
    .if (\n - 2 - \i) % 2
    adcx    %rax, %r9
    adox    %rax, %r9
    mov     %r9, dr(%rdi)
    .else
    adcx    %rax, %r8
    adox    %rax, %r8
    mov     %r8, dr(%rdi)
    .endif
.endm

# rp = 2 * rp + the diagonal, as DSTEP
.macro SDIAG n
    xor     %eax, %eax                  # CF = OF = 0
    .set    t, 0
    .rept   \n
    .set    du, 8 * t
    .set    dr, 16 * t
    .set    dr1, 16 * t + 8
    mov     du(%rsi), %rdx
    mulx    %rdx, %rax, %r8
    mov     dr(%rdi), %r9
    adox    %r9, %r9
    adcx    %rax, %r9
    mov     %r9, dr(%rdi)
    mov     dr1(%rdi), %r10
    adox    %r10, %r10
    adcx    %r8, %r10
    mov     %r10, dr1(%rdi)
    .set    t, t + 1
    .endr
.endm

.macro SQRN n
    .set    d, 8 * (2 * \n - 1)
    movq    $0, (%rdi)                  # rp[0]
    movq    $0, d(%rdi)                 # rp[2n-1]
    SROW0   \n
    .set    i, 1
    .rept   \n - 2
    SROW    i, \n
    .set    i, i + 1
    .endr
    SDIAG   \n
    ret
.endm

    .align  16, 0x90
    .globl  numetron_sqr_basecase_adx
    .hidden numetron_sqr_basecase_adx
    .type   numetron_sqr_basecase_adx, @function
numetron_sqr_basecase_adx:
    cmp     $16, %rdx
    ja      .Lgeneral
    lea     .Lstab(%rip), %rax
    movslq  -8(%rax,%rdx,4), %rcx       # entry n - 2
    add     %rax, %rcx
    jmp     *%rcx
    .irp    n, 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
    .p2align 4
.Ls\n:
    SQRN    \n
    .endr

    .p2align 2
.Lstab:
    .irp    n, 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
    .long   .Ls\n - .Lstab
    .endr

    .p2align 4
.Lgeneral:
    push    %rbx
    push    %rbp
    push    %r12
    push    %r13
    push    %r14
    push    %r15

    mov     %rdi, %r15
    mov     %rsi, %rbp
    mov     %rdx, %r14
    mov     %rsi, %r12                  # u[0]
    lea     8(%rdi), %rbx               # rp + 1
    lea     -1(%rdx), %r13              # L = n - 1
    movq    $0, (%rdi)                  # rp[0]
    lea     (%rdi,%rdx,8), %rax
    movq    $0, -8(%rax,%rdx,8)         # rp[2n-1]

# ---- row 0: rp[1..n] = u[1..n) * u[0] (one chain) ----
    mov     (%r12), %rdx
    ROWSETUP .Lmtab, 8(%r12), %rbx
    jmp     *%r11
    .irp    s, 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
.Lm\s:
    MSTEP   \s
    .endr
    lea     128(%rsi), %rsi
    lea     128(%rdi), %rdi
    lea     -1(%rcx), %rcx
    jrcxz   .Lmdone
    jmp     .Lm0
.Lmdone:
    mov     $0, %eax                    # mov keeps the flags
    adcx    %rax, %r9
    mov     %r9, (%rdi)                 # rp[n]

# ---- rows i = 1..n-17: rp[2i+1..i+n) += u[i+1..n) * u[i], rp[i+n] = the limb above ----
.Lrow:
    dec     %r13                        # L = n - 1 - i
    cmp     $16, %r13
    jb      .Ltail
    lea     8(%r12), %r12
    lea     16(%rbx), %rbx
    mov     (%r12), %rdx
    ROWSETUP .Latab, 8(%r12), %rbx
    jmp     *%r11
    .irp    s, 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
.La\s:
    ASTEP   \s
    .endr
    lea     128(%rsi), %rsi
    lea     128(%rdi), %rdi
    lea     -1(%rcx), %rcx
    jrcxz   .Ladone
    jmp     .La0
.Ladone:
    mov     $0, %eax
    adcx    %rax, %r9
    adox    %rax, %r9
    mov     %r9, (%rdi)                 # rp[i+n]
    jmp     .Lrow

# ---- the last 15 rows (L = 15..1): those of a 16-limb square of u's top 16 limbs, i = n-16
# .. n-2 -- the straight-line rows 0..14 of n = 16 at up + (n - 16), rp + 2 (n - 16) ----
.Ltail:
    lea     -128(%rbp,%r14,8), %rsi     # up + n - 16
    lea     -256(%r15,%r14,8), %rdi
    lea     (%rdi,%r14,8), %rdi         # rp + 2 (n - 16)
    .set    i, 0
    .rept   15
    SROW    i, 16
    .set    i, i + 1
    .endr

# ---- rp = 2 * rp + the diagonal ----
.Ldiag:
    mov     %r14, %r10
    neg     %r10
    and     $3, %r10                    # k = -n & 3, the entry step
    lea     3(%r14), %rcx
    shr     $2, %rcx                    # passes: ceil(n / 4)
    lea     .Ldtab(%rip), %r11
    movslq  (%r11,%r10,4), %rax
    add     %rax, %r11
    shl     $3, %r10
    mov     %rbp, %rsi
    sub     %r10, %rsi                  # up - k
    add     %r10, %r10
    mov     %r15, %rdi
    sub     %r10, %rdi                  # rp - 2k
    xor     %eax, %eax                  # CF = OF = 0
    jmp     *%r11
    .irp    s, 0,1,2,3
.Ld\s:
    DSTEP   \s
    .endr
    lea     32(%rsi), %rsi
    lea     64(%rdi), %rdi
    lea     -1(%rcx), %rcx
    jrcxz   .Lddone
    jmp     .Ld0
.Lddone:
    pop     %r15
    pop     %r14
    pop     %r13
    pop     %r12
    pop     %rbp
    pop     %rbx
    ret

    .p2align 2
.Lmtab:
    .irp    s, 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
    .long   .Lm\s - .Lmtab
    .endr
.Latab:
    .irp    s, 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
    .long   .La\s - .Latab
    .endr
.Ldtab:
    .irp    s, 0,1,2,3
    .long   .Ld\s - .Ldtab
    .endr
    .size   numetron_sqr_basecase_adx, .-numetron_sqr_basecase_adx

    .section .note.GNU-stack,"",@progbits
